#!/bin/bash

# scope

scope () {
	local lclVAR=1
	glbVAR=1
	echo "lcoal variable here is $lclVAR"
	echo "global variable here is $glbVAR"
}

scope

echo "lcoal variable outside is $lclVAR"
echo "global variable outside is $glbVAR"